CREATE OR REPLACE FUNCTION FNC_INTEREST(
  PRICE NUMBER) RETURN NUMBER
IS
  MYINTEREST NUMBER;
BEGIN
-- 가격이 30,000원 이상이면 10%, 30,000원 미만이면 5%
  IF PRICE >= 30000 THEN MYINTEREST := PRICE * 0.1;
  ELSE MYINTEREST := PRICE * 0.05;
  END IF;
  RETURN MYINTEREST;
END;
/