-- DESC EMP01
SELECT COLUMN_NAME,DATA_TYPE,DATA_LENGTH,NULLABLE FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'EMP01'

ALTER TABLE EMP01
ADD(JOB2 VARCHAR2(9)); 

-- DESC EMP01
SELECT COLUMN_NAME,DATA_TYPE,DATA_LENGTH,NULLABLE FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'EMP01'
