-- 테이블 스페이스 생성
CREATE TABLESPACE myts DATAFILE 
 'C:\prod\oraclexe\app\oracle\oradata\XE\myts.dbf' SIZE 100M AUTOEXTEND ON NEXT 5M;
 
 
-- 사용자 생성
CREATE USER ORA_USER IDENTIFIED BY HONG 
DEFAULT TABLESPACE MYTS
TEMPORARY TABLESPACE TEMP;

-- DBA 롤 부여
GRANT DBA TO ORA_USER;

