SELECT * FROM EMP;
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, COMM, DEPTNO 
FROM EMP;

-- 뷰의 기본 테이블
-- 뷰의 기본 테이블 생성하기
DROP TABLE DEPT_COPY;
CREATE TABLE DEPT_COPY
AS
SELECT * FROM DEPT;
DROP TABLE EMP_COPY;
CREATE TABLE EMP_COPY
AS
SELECT * FROM EMP;
SELECT * FROM DEPT_COPY;
SELECT * FROM EMP_COPY;


-- 뷰 정의하기
-- 뷰를 생성할 권한이 불충분한 경우
CREATE VIEW EMP_VIEW30
AS
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP_COPY
WHERE DEPTNO=30; -- SQL Error: ORA-01031: insufficient privileges
CONN system/sys
GRANT CREATE VIEW TO scott; -- system계정으로 로그인하여 뷰를 생성할 수 있는 권한을 부여한다.
CONN scott/tiger
SELECT * FROM EMP_VIEW30;

-- 뷰 정의하기
DROP VIEW EMP_VIEW30;
CREATE VIEW EMP_VIEW30
AS
SELECT EMPNO, ENAME, DEPTNO
FROM EMP_COPY
WHERE DEPTNO=30;
DESC EMP_VIEW30
SELECT * FROM EMP_VIEW30;


-- 단순뷰와 복합뷰
-- 단순 뷰의 컬럼에 별칭 부여하기
DESC EMP_VIEW30;
CREATE OR REPLACE
VIEW EMP_VIEW(사원번호, 사원명, 부서번호)
AS
SELECT EMPNO, ENAME, DEPTNO
FROM EMP_COPY;
SELECT * FROM EMP_VIEW
WHERE 부서번호=30;

-- 복합 뷰 만들기
CREATE OR REPLACE
VIEW EMP_VIEW_DEPT
AS
SELECT E.EMPNO, E.ENAME, E.SAL, E.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY EMPNO DESC;
SELECT * FROM EMP_VIEW_DEPT;

--뷰 삭제 알아보기
-- 뷰 삭제하기
SELECT VIEW_NAME, TEXT
FROM USER_VIEWS;  -- USER DICTIONARY 테이블
SELECT * FROM EMP_VIEW;
DROP VIEW EMP_VIEW;
SELECT * FROM EMP_VIEW;


--뷰 생성에 사용되는 다양한 옵션
--뷰 수정을 위한 OR REPLACE 옵션

--DROP VIEW EMP_VIEW30;
--CREATE VIEW EMP_VIEW30
CREATE OR REPLACE VIEW EMP_VIEW30
AS
SELECT EMPNO, ENAME, SAL, COMM, DEPTNO
FROM EMP_COPY
WHERE DEPTNO=30;


-- FORCE 옵션으로 기본 테이블 없이 뷰 생성하기
DESC EMPLOYEES
CREATE OR REPLACE VIEW EMPLOYEES_VIEW
AS
SELECT EMPNO, ENAME, DEPTNO
FROM EMPLOYEES
WHERE DEPTNO=30; -- SQL Error: ORA-00942: table or view does not exist

CREATE OR REPLACE FORCE VIEW NOTABLE_VIEW
AS
SELECT EMPNO, ENAME, DEPTNO
FROM EMPLOYEES
WHERE DEPTNO=30;
--SELECT * FROM NOTABLE_VIEW;

SELECT VIEW_NAME, TEXT
FROM USER_VIEWS;
-- NOFORCE는 뷰 생성의 디폴트값으로 FORCE의 반대 기능을 가진 옵션이다.
CREATE OR REPLACE NOFORCE VIEW EXISTTABLE_VIEW
AS
SELECT EMPNO, ENAME, DEPTNO
FROM EMPLOYEES
WHERE DEPTNO=30; -- SQL Error: ORA-00942: table or view does not exist

SELECT VIEW_NAME, TEXT
FROM USER_VIEWS;

CREATE OR REPLACE VIEW EXISTTABLE_VIEW
AS
SELECT EMPNO, ENAME, DEPTNO
FROM EMPLOYEES
WHERE DEPTNO=30;


--조건 컬럼값을 변경하지 못하게 하는 WITH CHECK OPTION
DROP VIEW VIEW_CHK30;
CREATE OR REPLACE VIEW VIEW_CHK30
AS
SELECT EMPNO, ENAME, SAL, COMM, DEPTNO
FROM EMP_COPY
WHERE DEPTNO=30;
--WHERE DEPTNO=30 WITH CHECK OPTION;

SELECT * FROM VIEW_CHK30;

UPDATE VIEW_CHK30 SET DEPTNO=20
WHERE SAL>=1200;
SELECT * FROM VIEW_CHK30;
SELECT * FROM EMP_COPY;


--기본 테이블 변경을 막는 WITH READ ONLY 옵션 WITH CHECK OPTION 비교
UPDATE VIEW_CHK30 SET COMM=1000;
SELECT * FROM VIEW_CHK30;

CREATE OR REPLACE VIEW VIEW_READ30
AS
SELECT EMPNO, ENAME, SAL, COMM, DEPTNO
FROM EMP_COPY
WHERE DEPTNO=30 WITH READ ONLY;

UPDATE VIEW_READ30 SET COMM=2000;
SELECT * FROM VIEW_READ30;


--뷰 활용하여 Top-N 구하기
--ROWNUM 컬럼 성격 파악하기
DESC EMP;
SELECT ROWNUM, EMPNO, ENAME, HIREDATE
FROM EMP;

SELECT EMPNO, ENAME, HIREDATE
FROM EMP
ORDER BY HIREDATE;

SELECT ROWNUM, EMPNO, ENAME, HIREDATE
FROM EMP
ORDER BY HIREDATE;

--인라인 뷰로 구하는 TOP-N의 개념
-- 급여(SAL)를 많이 받는 6~10째 사원을 출력하기 위해서는 인라인 뷰안에 또 다른 인라인 뷰를 사용해야 한다.
-- 또한 ROWNUM 칼럼에 별칭을 부여해야 검색이 가능하다.
SELECT * FROM EMP
ORDER BY SAL DESC;

SELECT ROWNUM, RNUM, ENAME, SAL FROM
(SELECT ROWNUM RNUM, ENAME, SAL FROM
(SELECT * FROM EMP ORDER BY SAL DESC))
WHERE RNUM BETWEEN 6 AND 10;
