--chap06
-- SUM()함수
SELECT SUM(SAL) 
FROM EMP;

SELECT SUM(COMM)
FROM EMP;

--AVG() 함수
SELECT AVG(SAL)
FROM EMP;

--MAX, MIN
SELECT MAX(SAL), MIN(SAL)
FROM EMP;

-- 그룹함수와 단순컬럼이 같이 사용하는 경우, 주의해야 함
SELECT MAX(SAL)
FROM EMP;

SELECT ENAME, MAX(SAL)
FROM EMP;  -- 오류 발생, ORA-00937: not a single-group group function

--로우 개수 구하는 COUNT()함수
SELECT COUNT(COMM) FROM EMP;
SELECT COUNT(*) FROM EMP;
SELECT COUNT(*), COUNT(COMM) FROM EMP;
SELECT COUNT(JOB) 업무수 FROM EMP;
SELECT COUNT(DISTINCT JOB) 업무수 FROM EMP;

-- 6.2 GROUP BY 절
SELECT DEPTNO FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO, AVG(SAL) FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO, MAX(SAL), MIN(SAL) FROM EMP
GROUP BY DEPTNO;

--6.3 HAVING 조건
SELECT DEPTNO, AVG(SAL) FROM EMP
GROUP BY DEPTNO
HAVING AVG(SAL) >= 2000;

SELECT DEPTNO, MAX(SAL), MIN(SAL) FROM EMP
GROUP BY DEPTNO
HAVING MAX(SAL) > 2900;


--6.4 집합 연산자
-- UNION
DROP TABLE EXP_GOODS_ASIA;
CREATE TABLE EXP_GOODS_ASIA (
    COUNTRY VARCHAR2(10),
    SEQ     NUMBER,
    GOODS   VARCHAR2(80)
);
INSERT INTO EXP_GOODS_ASIA VALUES ('한국', 1, '원유제외 석유류');
INSERT INTO EXP_GOODS_ASIA VALUES ('한국', 2, '자동차');
INSERT INTO EXP_GOODS_ASIA VALUES ('한국', 3, '전자집적회로');
INSERT INTO EXP_GOODS_ASIA VALUES ('한국', 4, '선박');
INSERT INTO EXP_GOODS_ASIA VALUES ('한국', 5, 'LCD');
INSERT INTO EXP_GOODS_ASIA VALUES ('한국', 6, '자동차부품');
INSERT INTO EXP_GOODS_ASIA VALUES ('한국', 7, '휴대전화');
INSERT INTO EXP_GOODS_ASIA VALUES ('한국', 8, '환식탄화수소');
INSERT INTO EXP_GOODS_ASIA VALUES ('한국', 9, '무선송신기 디스플레이 부속품');
INSERT INTO EXP_GOODS_ASIA VALUES ('한국', 10, '철 또는 비합금강');
INSERT INTO EXP_GOODS_ASIA VALUES ('일본', 1, '자동차');
INSERT INTO EXP_GOODS_ASIA VALUES ('일본', 2, '자동차부품');
INSERT INTO EXP_GOODS_ASIA VALUES ('일본', 3, '전자집적회로');
INSERT INTO EXP_GOODS_ASIA VALUES ('일본', 4, '선박');
INSERT INTO EXP_GOODS_ASIA VALUES ('일본', 5, '반도체웨이퍼');
INSERT INTO EXP_GOODS_ASIA VALUES ('일본', 6, '화물차');
INSERT INTO EXP_GOODS_ASIA VALUES ('일본', 7, '원유제외 석유류');
INSERT INTO EXP_GOODS_ASIA VALUES ('일본', 8, '건설기계');
INSERT INTO EXP_GOODS_ASIA VALUES ('일본', 9, '다이오드, 트랜지스터');
INSERT INTO EXP_GOODS_ASIA VALUES ('일본', 10, '기계류');
SELECT COUNT(*) FROM EXP_GOODS_ASIA;
COMMIT;

SELECT GOODS FROM EXP_GOODS_ASIA
WHERE COUNTRY='한국' 
UNION
SELECT GOODS FROM EXP_GOODS_ASIA
WHERE COUNTRY='일본';

--6.4.2 UNION ALL
SELECT GOODS FROM EXP_GOODS_ASIA
WHERE COUNTRY='한국' 
UNION ALL
SELECT GOODS FROM EXP_GOODS_ASIA
WHERE COUNTRY='일본';

--6.4.3 INTERSECT
SELECT GOODS FROM EXP_GOODS_ASIA
WHERE COUNTRY='한국' 
INTERSECT
SELECT GOODS FROM EXP_GOODS_ASIA
WHERE COUNTRY='일본';

6.4.4 MINUS
SELECT GOODS
FROM EXP_GOODS_ASIA
WHERE COUNTRY = '한국'
MINUS
SELECT GOODS
FROM EXP_GOODS_ASIA
WHERE COUNTRY = '일본';

SELECT GOODS
FROM EXP_GOODS_ASIA
WHERE COUNTRY = '일본'
MINUS
SELECT GOODS
FROM EXP_GOODS_ASIA
WHERE COUNTRY = '한국';

-- 6.4.5 집합 연산자 제한사항
-- 집합 연산자 제한사항
--1. 집합 연산자로 연결되는 각 SELECT문의 SELECT 리스트의 
--개수와 데이터 타입은 일치해야 한다.
SELECT GOODS FROM EXP_GOODS_ASIA
WHERE COUNTRY = '한국'
UNION
SELECT SEQ, GOODS FROM EXP_GOODS_ASIA
WHERE COUNTRY = '일본';

SELECT SEQ
FROM EXP_GOODS_ASIA
WHERE COUNTRY = '한국'
UNION
SELECT GOODS
FROM EXP_GOODS_ASIA
WHERE COUNTRY = '일본';
--ORA-01790: 대응하는 식과 같은 데이터 유형이어야 합니다
--01790. 00000 - "expression must have same datatype as corresponding expression"

--2. 집합 연산자로 SELECT 문을 연결할 때 ORDER BY절은 
-- 맨 마지막 문장에서만 사용할 수 있다.
SELECT GOODS
FROM EXP_GOODS_ASIA
WHERE COUNTRY = '한국'
ORDER BY GOODS
UNION
SELECT GOODS
FROM EXP_GOODS_ASIA
WHERE COUNTRY = '일본';
--ORA-00933: SQL 명령어가 올바르게 종료되지 않았습니다
--00933. 00000 - "SQL command not properly ended"
SELECT GOODS
FROM EXP_GOODS_ASIA
WHERE COUNTRY = '한국'
UNION
SELECT GOODS
FROM EXP_GOODS_ASIA
WHERE COUNTRY = '일본'
ORDER BY GOODS;