--chap13

INSERT INTO DEPT
VALUES(10, 'TEST', 'SEOUL');
-- 오류발생: 무결성 제약 조건에 위배됩니다.

-- DESC DEPT
SELECT COLUMN_NAME,DATA_TYPE,DATA_LENGTH,NULLABLE FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'DEPT';

SELECT * FROM DEPT;

-- DESC USER_CONSTRAINTS;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='DEPT';

-- 필수 입력을 위한 NOT NULL 제약 조건
-- NOT NULL 제약 조건을 설정하지 않고 테이블 생성하기
DROP TABLE EMP01;
CREATE TABLE EMP01(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    DEPTNO NUMBER(2)
);
SELECT * FROM EMP01;

INSERT INTO EMP01
VALUES(NULL, NULL, 'SALESMAN', 30);

-- NOT NULL 제약 조건을 설정하여 테이블 생성하기
DROP TABLE EMP02;
CREATE TABLE EMP02(
    EMPNO NUMBER(4) NOT NULL,
    ENAME VARCHAR2(10) NOT NULL,
    JOB VARCHAR2(9),
    DEPTNO NUMBER(2)
);
INSERT INTO EMP02
VALUES(NULL, NULL, 'SALESMAN', 30); -- 오류발생: cannot insert NULL into ("SCOTT"."EMP02"."EMPNO")
-- DESC EMP02
SELECT COLUMN_NAME,DATA_TYPE,DATA_LENGTH,NULLABLE FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'EMP02';

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='EMP02';

INSERT INTO EMP02
VALUES(7499, 'ALLEN', 'SALESMAN', 30);

SELECT * FROM EMP02;


-- 유일한 값만 허용하는 UNIQUE 제약 조건
-- UNIQUE 제약 조건을 설정하여 테이블 생성하기
DROP TABLE EMP03;
CREATE TABLE EMP03(
    EMPNO NUMBER(4) UNIQUE,
    ENAME VARCHAR2(10) NOT NULL,
    JOB VARCHAR2(9),
    DEPTNO NUMBER(2)
);
INSERT INTO EMP03
VALUES(7499, 'ALLEN', 'SALESMAN', 30);
SELECT * FROM EMP03;
INSERT INTO EMP03
VALUES(7499, 'JONES', 'MANAGER', 20);
INSERT INTO EMP03
VALUES(NULL, 'JONES', 'MANAGER', 20); -- 오류발생: unique constraint (SCOTT.SYS_C0011406) violated
INSERT INTO EMP03
VALUES(NULL, 'JONES', 'SALESMAN', 10); -- UNIQUE는 NULL값은 예외로 간주한다.
SELECT * FROM EMP03; -- 만약 NULL값도 입력되지 않게 제한하려면 UNIQUE NOT NULL처럼 기술하면 된다.


-- 컬럼 레벨로 제약 조건명을 명시하여 제약 조건 설정하기
-- 예: 컬럼 레벨로 제약 조건명 명시하기
DROP TABLE EMP04;
CREATE TABLE EMP04(
    EMPNO NUMBER(4) CONSTRAINT EMP04_EMPNO_UK UNIQUE
);
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='EMP04';


-- 데이터 구분을 위한 PRIMARY KEY 제약 조건
-- PRIMARY KEY 제약 조건 설정하기
-- PRIMARY KEY = UNIQUE + NOT NULL
DROP TABLE EMP05;
CREATE TABLE EMP05(
    EMPNO NUMBER(4) CONSTRAINT EMP05_EMPNO_PK PRIMARY KEY,
    ENAME VARCHAR2(10) CONSTRAINT EMP05_ENAME_NN NOT NULL,
    JOB VARCHAR2(9),
    DEPTNO NUMBER(2)
);
INSERT INTO EMP05 VALUES(7499,'ALLEN','SALESMAN',30);
SELECT * FROM EMP05;
INSERT INTO EMP05 VALUES(7499,'JONES','MANAGER',20); -- SQL Error: ORA-00001: unique constraint (SCOTT.EMP05_EMPNO_PK) violated
INSERT INTO EMP05 VALUES(NULL,'JONES','MANAGER',20); -- SQL Error: ORA-01400: cannot insert NULL into ("SCOTT"."EMP05"."EMPNO")


-- 참조 무결성을 위한 FOREIGN KEY 제약 조건
-- 다음은 EMP 테이블과 DEPT 테이블의 제약 조건을 확인한다.
SELECT TABLE_NAME, CONSTRAINT_TYPE,
CONSTRAINT_NAME, R_CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('DEPT', 'EMP');

-- 왜래 키 제약 조건 설정하기
DROP TABLE EMP06;
CREATE TABLE EMP06(
    EMPNO NUMBER(4) CONSTRAINT EMP06_EMPNO_PK PRIMARY KEY ,
    ENAME VARCHAR2(10) CONSTRAINT EMP06_ENAME_NN NOT NULL,
    JOB VARCHAR2(9),
    DEPTNO NUMBER(2) CONSTRAINT EMP06_DEPTNO_FK REFERENCES DEPT(DEPTNO)
);
INSERT INTO EMP06 VALUES(7499,'ALLEN','SALESMAN',30);
SELECT * FROM EMP06;
SELECT * FROM DEPT;
INSERT INTO EMP06 VALUES(7499,'JONES','MANAGER',50); -- SQL Error: ORA-00001: unique constraint (SCOTT.EMP06_EMPNO_PK) violated
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, R_CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='EMP06';


-- CHECK와 DEFAULT의 제약 조건
-- CHECK 제약 조건 설정하기
DROP TABLE EMP07;
CREATE TABLE EMP07(
    EMPNO NUMBER(4) CONSTRAINT EMP07_EMPNO_PK PRIMARY KEY,
    ENAME VARCHAR2(10) CONSTRAINT EMP07_ENAME_NN NOT NULL,
    SAL NUMBER(7,2) CONSTRAINT EMP07_SAL_CK CHECK(SAL BETWEEN 500 AND 5000),
    GENDER VARCHAR2(1) CONSTRAINT EMP07_GENDER_CK CHECK(GENDER IN('M','F'))
);
INSERT INTO EMP07 VALUES(7499,'ALLEN',500,'M');
INSERT INTO EMP07 VALUES(7498,'ALLEN',7000,'A'); -- SQL Error: ORA-02290: check constraint (SCOTT.EMP07_GENDER_CK) violated
SELECT TABLE_NAME, CONSTRAINT_TYPE, CONSTRAINT_NAME, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='EMP07';

-- DEFAULT 제약 조건 설정하기
DROP TABLE DEPT01;
CREATE TABLE DEPT01(
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13) DEFAULT 'SEOUL'
);
INSERT INTO DEPT01(DEPTNO,DNAME) VALUES(10,'ACCOUNTING');
INSERT INTO DEPT01 VALUES(20,'ACCOUNTING','BUSAN');
SELECT * FROM DEPT01;


-- 테이블 레벨 방식으로 제약 조건 지정하기
-- 컬럼 레벨로 제약 조건을 지정하는 방법
DROP TABLE EMP01;
CREATE TABLE EMP01(
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(10) NOT NULL,
    JOB VARCHAR2(9) UNIQUE,
    DEPTNO NUMBER(4) REFERENCES DEPT(DEPTNO)
);
-- 테이블 레벨로 제약 조건을 지정하는 방법
DROP TABLE EMP02;
CREATE TABLE EMP02(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10) NOT NULL,
    JOB VARCHAR2(9),
    DEPTNO NUMBER(4),
    --PRIMARY KEY(EMPNO, JOB), -- 복합키 
    UNIQUE(JOB),
    FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO)
);
ALTER TABLE EMP02
ADD PRIMARY KEY(EMPNO);


-- CASCADE 옵션
-- CASCADE 옵션으로 제약 조건 연속적으로 비활성화 / 제거하기
DROP TABLE DEPT01;
DROP TABLE DEPT01 CASCADE CONSTRAINTS;
CREATE TABLE DEPT01
AS
SELECT * FROM DEPT;

ALTER TABLE DEPT01
ADD CONSTRAINT DEPT01_DEPTNO_PK PRIMARY KEY (DEPTNO);
DESC DEPT01;
DROP TABLE EMP01 CASCADE CONSTRAINTS;
CREATE TABLE EMP01
AS
SELECT * FROM EMP WHERE 1=0;
ALTER TABLE EMP01
ADD CONSTRAINT EMP01_DEPTNO_FK FOREIGN KEY(DEPTNO) REFERENCES DEPT01(DEPTNO);
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE,
TABLE_NAME, R_CONSTRAINT_NAME, STATUS
FROM USER_CONSTRAINTS  -- USER DICTIONARY 테이블: ORALCE을 자동 생성함
WHERE TABLE_NAME IN('DEPT01', 'EMP01');
SELECT * FROM DEPT01;
SELECT * FROM EMP01;
INSERT INTO EMP01 (DEPTNO) VALUES (10);
SELECT * FROM EMP01;
INSERT INTO EMP01 (DEPTNO) VALUES (50);
ALTER TABLE DEPT01
DROP PRIMARY KEY CASCADE;
