-- 인덱스 정보 조회
SELECT INDEX_NAME, TABLE_NAME , COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE TABLE_NAME IN('EMP', 'DEPT');


--조회 속도 비교하기
-- 사원 테이블 복사하기
DROP TABLE EMP01;
CREATE TABLE EMP01
AS
SELECT * FROM EMP;
SELECT TABLE_NAME, INDEX_NAME, COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE TABLE_NAME IN('EMP', 'EMP01');
SELECT * FROM EMP01;
-- 인덱스가 아닌 컬럼으로 검색하기
INSERT INTO EMP01 SELECT * FROM EMP01;
--... 테이블 자체 복사를 여러 번 반복해서 상당히 많은 양의 행을 생성한다.
INSERT INTO EMP01 SELECT * FROM EMP01;
INSERT INTO EMP01(EMPNO, ENAME) VALUES(1111, 'SYJ');
SET TIMING ON
SELECT DISTINCT EMPNO, ENAME
FROM EMP01
WHERE ENAME='SYJ';


--인덱스 설정하여 조회속도 비교하기
-- 인덱스 설정하기
CREATE INDEX IDX_EMP01_ENAME
ON EMP01(ENAME, EMPNO);
SELECT DISTINCT EMPNO, ENAME
FROM EMP01
WHERE ENAME='SYJ';

SELECT COUNT(*) FROM EMP01;
SELECT EMPNO FROM EMP01
WHERE EMPNO=1111;

-- 인덱스 제거하기
SELECT INDEX_NAME, TABLE_NAME , COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE TABLE_NAME IN('EMP01');

DROP INDEX IDX_EMP01_ENAME;
SELECT DISTINCT EMPNO, ENAME
FROM EMP01
WHERE ENAME='SYJ';


-- 고유 인덱스와 비고유 인덱스 정의하기
DROP TABLE DEPT01;
CREATE TABLE DEPT01
AS
SELECT * FROM DEPT WHERE 1=0;
INSERT INTO DEPT01 VALUES(10, '인사과', '서울');
INSERT INTO DEPT01 VALUES(20, '총무과', '대전');
INSERT INTO DEPT01 VALUES(30, '교육팀', '대전');
SELECT * FROM DEPT01;
CREATE UNIQUE INDEX IDX_DEPT01_DEPTNO
ON DEPT01(DEPTNO);
CREATE UNIQUE INDEX IDX_DEPT01_LOC
ON DEPT01(LOC);
-- 중복된 데이터를 갖는 컬럼을 인텍스로 지정하면 오류가 발생한다.
CREATE INDEX IDX_DEPT01_LOC
ON DEPT01(LOC);


--결합 인덱스 정의하기
CREATE INDEX IDX_DEPT01_COM
ON DEPT01(DEPTNO, DNAME);
SELECT INDEX_NAME, COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE TABLE_NAME = 'DEPT01';

SELECT * FROM DEPT01
WHERE DEPTNO=10 AND DNAME = '인사과';


--함수 기반 인덱스 정의하기
SET TIMING ON
-- 인덱스 이전 검색하기
SELECT * FROM EMP01
WHERE SAL*12 = 3600;
CREATE INDEX IDX_EMP01_ANNSAL
ON EMP01(SAL*12);

SELECT INDEX_NAME, COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE TABLE_NAME = 'EMP01';

-- 인덱스 이후 검색하기
SELECT * FROM EMP01
WHERE SAL*12 = 3600;